Repository prgrms-be-devcourse/BE-03-Prolog, pull requests merged in 2023-01, with the labels that each got.

#2 [#1] 어플리케이션 환경 설정 및 Flyway 추가
  build.gradle
  src/main/java/com/prgrms/prolog/DatabaseConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/logback.xml
Labels: 🛠️ config

#21 [#5, #6] 공통 엔티티 및 User 엔티티 구현
  src/main/java/com/prgrms/prolog/PrologApplication.java
  src/main/java/com/prgrms/prolog/global/common/BaseEntity.java
  src/main/java/com/prgrms/prolog/global/config/DatabaseConfig.java
  src/main/java/com/prgrms/prolog/user/model/User.java
Labels: ✨ feat

#23 [#6] User 엔티티 리팩터링 및 테스트 추가
  src/main/java/com/prgrms/prolog/user/model/User.java
  src/test/java/com/prgrms/prolog/user/model/UserTest.java
Labels: ♻️ refactor, ✅ test

#22 [#7, #8] Post 및 Comment 엔티티 구현
  src/main/java/com/prgrms/prolog/domain/comment/model/Comment.java
  src/main/java/com/prgrms/prolog/domain/post/model/Post.java
Labels: ✨ feat

#24 [#11] 요청 데이터 logging 기능 구현
  src/main/java/com/prgrms/prolog/global/log/CustomRequestLoggingFilter.java
Labels: ✨ feat

#25 [#4] 엔티티 리팩터링 및 테스트 추가
  src/main/java/com/prgrms/prolog/domain/comment/model/Comment.java
  src/main/java/com/prgrms/prolog/domain/post/model/Post.java
  src/main/java/com/prgrms/prolog/domain/user/model/User.java
  src/main/java/com/prgrms/prolog/global/common/BaseEntity.java
  src/test/java/com/prgrms/prolog/domain/comment/model/CommentTest.java
  src/test/java/com/prgrms/prolog/domain/post/model/PostTest.java
  src/test/java/com/prgrms/prolog/domain/user/model/UserTest.java
  src/test/java/com/prgrms/prolog/utils/TestUtils.java
Labels: ♻️ refactor, ✅ test

#29 [#28] 데이터 요청 logging 어노테이션 설정 수정
  src/main/java/com/prgrms/prolog/global/log/CustomRequestLoggingFilter.java
Labels: 🐛 bug

#27 [#26] Jacoco 적용하기
  build.gradle
Labels: 🔧 add, 🛠️ config

#33 [#15] github action으로 자동빌드 및 테스트
  .github/workflows/gradle-build.yml
  src/main/resources/application.yml
Labels: 🐥CI/CD

#34 [#14] 전역 예외처리 핸들링 기능 구현
  src/main/java/com/prgrms/prolog/global/dto/ErrorResponse.java
  src/main/java/com/prgrms/prolog/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: ✨ feat

#35 [#31] JWT 기능 구현
  build.gradle
  src/main/java/com/prgrms/prolog/global/config/SecurityConfig.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtTokenProvider.java
  src/main/resources/application-security.yml
  src/main/resources/application.yml
Labels: ✨ feat

#36 [#16] 디폴트 회원 가입 및 로그인 기능 구현
  src/main/java/com/prgrms/prolog/domain/user/api/UserController.java
  src/main/java/com/prgrms/prolog/domain/user/dto/UserDto.java
  src/main/java/com/prgrms/prolog/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/prolog/domain/user/service/UserService.java
  src/main/java/com/prgrms/prolog/domain/user/service/UserServiceImpl.java
Labels: ✨ feat

#37 [#30] MessageSource 설정 및 메시지 관리 구현
  src/main/java/com/prgrms/prolog/global/config/MessageConfig.java
  src/main/java/com/prgrms/prolog/global/util/MessageUtil.java
  src/main/resources/application.yml
  src/main/resources/messages/exceptions/exception.properties
  src/main/resources/messages/logs/log-form.properties
Labels: ✨ feat

#39 [#38] SpringBoot profiles별 실행 환경 분리 설정
  src/main/resources/application-db.yml
  src/main/resources/application-exception.yml
  src/main/resources/application.yml
Labels: 🔧 add, 🛠️ config

#40 [#17] docker image를 docker hub에 배포하기
  .github/workflows/docker-push.yml
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: 🐥CI/CD

#41 [#12] restdocs-swagger 변환 설정 추가
  build.gradle
  src/test/java/com/prgrms/prolog/config/RestDocsConfig.java
Labels: 🔧 add

#43 [#9] User 각 레이어 단위 테스트
  src/main/java/com/prgrms/prolog/domain/user/model/User.java
  src/main/java/com/prgrms/prolog/global/common/BaseEntity.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/prgrms/prolog/domain/user/Repository/UserRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/user/api/UserControllerTest.java
  src/test/java/com/prgrms/prolog/domain/user/service/UserServiceTest.java
  src/test/java/com/prgrms/prolog/utils/TestUtils.java
Labels: ✅ test, 🔧 update

#42 [#32] OAuth 로그인 기능 구현
  build.gradle
  src/main/java/com/prgrms/prolog/PrologApplication.java
  src/main/java/com/prgrms/prolog/domain/user/dto/UserDto.java
  src/main/java/com/prgrms/prolog/global/common/BaseEntity.java
  src/main/java/com/prgrms/prolog/global/config/JpaConfig.java
  src/main/java/com/prgrms/prolog/global/config/SecurityConfig.java
  src/main/java/com/prgrms/prolog/global/oauth/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/prolog/global/oauth/OAuthProvider.java
  src/main/java/com/prgrms/prolog/global/oauth/OAuthService.java
  src/main/resources/application-security.yml
Labels: ✨ feat

#49 [#19] 게시물 CRUD 및 테스트
  src/main/java/com/prgrms/prolog/domain/post/api/PostController.java
  src/main/java/com/prgrms/prolog/domain/post/dto/PostRequest.java
  src/main/java/com/prgrms/prolog/domain/post/dto/PostResponse.java
  src/main/java/com/prgrms/prolog/domain/post/model/Post.java
  src/main/java/com/prgrms/prolog/domain/post/repository/PostRepository.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostService.java
  src/main/java/com/prgrms/prolog/domain/user/dto/UserResponse.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/prgrms/prolog/domain/post/api/PostControllerTest.java
  src/test/java/com/prgrms/prolog/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/post/service/PostServiceTest.java
Labels: ✨ feat, ♻️ refactor, ✅ test

#51 [#46] db 설정을 외부에서 설정할 수 있도록 환경 변수로 분리하기
  .github/workflows/docker-push-and-aws-run.yml
  .github/workflows/gradle-build.yml
  Dockerfile
  src/main/java/com/prgrms/prolog/global/config/DatabaseConfig.java
  src/main/resources/application-db.yml
  src/main/resources/application.yml
Labels: 🐛 bug, 🐥CI/CD

#57 [#56] OAuth redirect-uri를 localhost에서 실제 AWS서버 주소로 변경
  .github/workflows/docker-push-and-aws-run.yml
  Dockerfile
  docker-compose.yml
  src/main/resources/application-security.yml
Labels: 🔧 update, 🛠️ config

#68 Release Prolog v1.0.1
  .github/workflows/docker-push-and-aws-run.yml
  Dockerfile
  docker-compose.yml
  src/main/resources/application-security.yml
Labels: release

#70 [#69] Restdocs asciidoc 빌드 설정 업데이트
  build.gradle
Labels: 🔧 update

#72 [#71] 테스트 컨테이너 적용하기
  src/main/java/com/prgrms/prolog/domain/comment/api/CommentController.java
  src/main/java/com/prgrms/prolog/domain/user/api/UserController.java
  src/main/java/com/prgrms/prolog/global/config/DatabaseConfig.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthentication.java
  src/main/resources/application-db.yml
  src/test/java/com/prgrms/prolog/config/TestContainerConfig.java
  src/test/java/com/prgrms/prolog/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/post/api/PostControllerTest.java
  src/test/java/com/prgrms/prolog/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/post/service/PostServiceTest.java
  src/test/java/com/prgrms/prolog/domain/user/Repository/UserRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/user/api/UserControllerTest.java
  src/test/java/com/prgrms/prolog/utils/TestUtils.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: ♻️ refactor, ✅ test

#73 Github Action 리펙토링 및 관련 부분 README 업데이트
  .github/workflows/docker-push-and-aws-run.yml
  .github/workflows/gradle-build.yml
  Dockerfile
  README.md
  docker-compose.yml
  src/main/resources/application-db.yml
Labels: 📝 docs, ♻️ refactor, 🐥CI/CD

#74 [#66] Jwt & OAuth 리팩터링 및 테스트 추가
  build.gradle
  src/main/java/com/prgrms/prolog/domain/comment/api/CommentController.java
  src/main/java/com/prgrms/prolog/domain/comment/service/CommentService.java
  src/main/java/com/prgrms/prolog/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/post/api/PostController.java
  src/main/java/com/prgrms/prolog/domain/post/dto/PostResponse.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostService.java
  src/main/java/com/prgrms/prolog/domain/user/api/UserController.java
  src/main/java/com/prgrms/prolog/domain/user/dto/UserDto.java
  src/main/java/com/prgrms/prolog/domain/user/model/User.java
  src/main/java/com/prgrms/prolog/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/prolog/domain/user/service/UserService.java
  src/main/java/com/prgrms/prolog/domain/user/service/UserServiceImpl.java
  src/main/java/com/prgrms/prolog/global/config/JpaConfig.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/prolog/global/oauth/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/prolog/global/oauth/OAuthProvider.java
  src/main/java/com/prgrms/prolog/global/oauth/OAuthService.java
  src/main/resources/application-security.yml
  src/main/resources/db/migration/V2__add_profile_img_url.sql
  src/test/java/com/prgrms/prolog/config/JwtConfig.java
  src/test/java/com/prgrms/prolog/domain/comment/api/CommentControllerTest.java
  src/test/java/com/prgrms/prolog/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/comment/service/CommentServiceImplTest.java
  src/test/java/com/prgrms/prolog/domain/post/api/PostControllerTest.java
  src/test/java/com/prgrms/prolog/domain/post/service/PostServiceTest.java
  src/test/java/com/prgrms/prolog/domain/user/Repository/UserRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/user/api/UserControllerTest.java
  src/test/java/com/prgrms/prolog/domain/user/service/UserServiceTest.java
  src/test/java/com/prgrms/prolog/global/jwt/JwtAuthenticationTest.java
  src/test/java/com/prgrms/prolog/global/jwt/JwtTokenProviderTest.java
  src/test/java/com/prgrms/prolog/utils/TestUtils.java
  src/test/resources/application.yml
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  src/test/resources/schema.sql
Labels: ♻️ refactor, ✅ test

#75 [#59] 태그 API 기능 구현
  src/main/java/com/prgrms/prolog/domain/comment/model/Comment.java
  src/main/java/com/prgrms/prolog/domain/post/api/PostController.java
  src/main/java/com/prgrms/prolog/domain/post/dto/PostRequest.java
  src/main/java/com/prgrms/prolog/domain/post/dto/PostResponse.java
  src/main/java/com/prgrms/prolog/domain/post/model/Post.java
  src/main/java/com/prgrms/prolog/domain/post/repository/PostRepository.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostService.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/posttag/dto/PostTagDto.java
  src/main/java/com/prgrms/prolog/domain/posttag/model/PostTag.java
  src/main/java/com/prgrms/prolog/domain/posttag/repository/PostTagRepository.java
  src/main/java/com/prgrms/prolog/domain/roottag/model/RootTag.java
  src/main/java/com/prgrms/prolog/domain/roottag/repository/RootTagRepository.java
  src/main/java/com/prgrms/prolog/domain/roottag/util/TagConverter.java
  src/main/java/com/prgrms/prolog/domain/user/model/User.java
  src/main/java/com/prgrms/prolog/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/prolog/domain/usertag/model/UserTag.java
  src/main/java/com/prgrms/prolog/domain/usertag/repository/UserTagRepository.java
  src/main/java/com/prgrms/prolog/global/config/SecurityConfig.java
  src/main/resources/db/migration/V2.1__add_tag_table.sql
  src/test/java/com/prgrms/prolog/domain/comment/service/CommentServiceImplTest.java
  src/test/java/com/prgrms/prolog/domain/post/api/PostControllerTest.java
  src/test/java/com/prgrms/prolog/domain/post/service/PostServiceTest.java
  src/test/java/com/prgrms/prolog/domain/posttag/model/PostTagTest.java
  src/test/java/com/prgrms/prolog/domain/roottag/model/RootTagTest.java
  src/test/java/com/prgrms/prolog/domain/roottag/repository/RootTagRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/user/Repository/UserRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/usertag/model/UserTagTest.java
  src/test/java/com/prgrms/prolog/utils/TestUtils.java
  src/test/resources/schema.sql
Labels: ✨ feat

#76 [#65] Nginx를 사용한 무중단 배포
  .github/workflows/docker-push-and-aws-run.yml
  deploy.sh
  docker-compose.yml
  nginx/default.conf
Labels: 🐥CI/CD

#78 [#77] 태그 및 카카오 프로필 이미지 문제 해결
  src/main/java/com/prgrms/prolog/domain/posttag/model/PostTag.java
  src/main/java/com/prgrms/prolog/domain/roottag/model/RootTag.java
  src/main/java/com/prgrms/prolog/domain/usertag/model/UserTag.java
  src/main/resources/application-db.yml
  src/main/resources/application-security.yml
Labels: 🐛 bug

#84 [#81] 로그 관리 설정, log4jdbc 설정
  build.gradle
  src/main/java/com/prgrms/prolog/global/exception/GlobalExceptionHandler.java
  src/main/resources/appender/console-appender.xml
  src/main/resources/appender/error-file-appender.xml
  src/main/resources/appender/info-file-appender.xml
  src/main/resources/appender/sql-file-appender.xml
  src/main/resources/appender/warn-file-appender.xml
  src/main/resources/application-db.yml
  src/main/resources/log4jdbc.log4j2.properties
  src/main/resources/logback.xml
Labels: 🔧 add

#82 [#62] 최근 포스트 목록 조회 API 개발하기
  src/main/java/com/prgrms/prolog/domain/post/api/PostController.java
Labels: ✨ feat, 🔧 add

#87 [#63] 좋아요 생성/취소 기능 및 해당 게시물에 대한 좋아요 개수 기능 추가
  src/main/java/com/prgrms/prolog/domain/like/api/LikeController.java
  src/main/java/com/prgrms/prolog/domain/like/dto/LikeDto.java
  src/main/java/com/prgrms/prolog/domain/like/model/Like.java
  src/main/java/com/prgrms/prolog/domain/like/repository/LikeRepository.java
  src/main/java/com/prgrms/prolog/domain/like/service/LikeService.java
  src/main/java/com/prgrms/prolog/domain/like/service/LikeServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/post/model/Post.java
  src/main/java/com/prgrms/prolog/domain/post/repository/PostRepository.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostService.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/user/dto/UserDto.java
  src/main/resources/db/migration/V2.2__add_like_table.sql
  src/main/resources/messages/exceptions/exception.properties
  src/test/java/com/prgrms/prolog/domain/like/api/LikeControllerTest.java
  src/test/java/com/prgrms/prolog/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/like/service/LikeServiceTest.java
  src/test/java/com/prgrms/prolog/domain/post/api/PostControllerTest.java
  src/test/java/com/prgrms/prolog/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/prolog/utils/TestUtils.java
  src/test/resources/schema.sql
Labels: ✨ feat, ✅ test, 🔧 update

#88 [#86] SpringBoot Actuator 추가
  build.gradle
  src/main/java/com/prgrms/prolog/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 💬 discussion, 🔧 add, 🛠️ config

#90 [#91] 게시물에 대한 좋아요 개수를 PostResponse에 추가
  src/main/java/com/prgrms/prolog/domain/like/api/LikeController.java
  src/main/java/com/prgrms/prolog/domain/post/dto/PostResponse.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostServiceImpl.java
  src/main/resources/logback.xml
  src/test/java/com/prgrms/prolog/domain/like/api/LikeControllerTest.java
  src/test/java/com/prgrms/prolog/domain/post/api/PostControllerTest.java
Labels: 🔧 update, 🛠️ config

#85 [#60] s3에 파일(이미지) 업로드하는 api 구현
  build.gradle
  src/main/java/com/prgrms/prolog/global/image/api/ImageController.java
  src/main/java/com/prgrms/prolog/global/image/dto/UploadFileResponse.java
  src/main/java/com/prgrms/prolog/global/image/util/FileManager.java
  src/main/java/com/prgrms/prolog/global/image/util/UploadFileToS3.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
  src/main/resources/messages/exceptions/exception.properties
  src/test/resources/application.yml
Labels: ✨ feat
