Repository prgrms-be-devcourse/BE-03-Prolog, pull requests merged in 2023-02, with the labels that each got.

#94 테스트 코드 추상화 작업
  src/main/java/com/prgrms/prolog/domain/series/api/SeriesController.java
  src/main/java/com/prgrms/prolog/domain/series/service/SeriesService.java
  src/main/java/com/prgrms/prolog/domain/series/service/SeriesServiceImpl.java
  src/test/java/com/prgrms/prolog/base/ControllerTest.java
  src/test/java/com/prgrms/prolog/base/RepositoryTest.java
  src/test/java/com/prgrms/prolog/base/ServiceTest.java
  src/test/java/com/prgrms/prolog/config/TestContainerConfig.java
  src/test/java/com/prgrms/prolog/domain/comment/api/CommentControllerTest.java
  src/test/java/com/prgrms/prolog/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/comment/service/CommentServiceImplTest.java
  src/test/java/com/prgrms/prolog/domain/like/api/LikeControllerTest.java
  src/test/java/com/prgrms/prolog/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/like/service/LikeServiceTest.java
  src/test/java/com/prgrms/prolog/domain/post/api/PostControllerTest.java
  src/test/java/com/prgrms/prolog/domain/post/model/PostTest.java
  src/test/java/com/prgrms/prolog/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/post/service/PostServiceTest.java
  src/test/java/com/prgrms/prolog/domain/roottag/repository/RootTagRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/series/api/SeriesControllerTest.java
  src/test/java/com/prgrms/prolog/domain/series/repository/SeriesRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/series/service/SeriesServiceImplTest.java
  src/test/java/com/prgrms/prolog/domain/user/Repository/UserRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/user/api/UserControllerTest.java
  src/test/java/com/prgrms/prolog/domain/user/service/UserServiceTest.java
  src/test/java/com/prgrms/prolog/utils/TestUtils.java
Labels: ♻️ refactor, ✅ test

#103 [#99] soft delete 적용
  src/main/java/com/prgrms/prolog/domain/comment/model/Comment.java
  src/main/java/com/prgrms/prolog/domain/post/model/Post.java
  src/main/java/com/prgrms/prolog/domain/series/model/Series.java
  src/main/java/com/prgrms/prolog/domain/user/model/User.java
  src/main/java/com/prgrms/prolog/global/common/BaseEntity.java
  src/main/resources/db/migration/V3__add_soft_deleted_field.sql
  src/test/resources/schema.sql
Labels: ✨ feat

#98 rest docs 업데이트
  src/docs/asciidoc/api.adoc
Labels: 📝 docs, ✅ test

#104 [#100] 메시지 소스 키 관리 리팩터링
  src/main/java/com/prgrms/prolog/domain/comment/model/Comment.java
  src/main/java/com/prgrms/prolog/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/like/service/LikeServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/post/model/Post.java
  src/main/java/com/prgrms/prolog/domain/post/service/PostServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/posttag/model/PostTag.java
  src/main/java/com/prgrms/prolog/domain/roottag/model/RootTag.java
  src/main/java/com/prgrms/prolog/domain/series/model/Series.java
  src/main/java/com/prgrms/prolog/domain/series/service/SeriesServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/user/model/User.java
  src/main/java/com/prgrms/prolog/domain/user/service/UserServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/usertag/model/UserTag.java
  src/main/java/com/prgrms/prolog/global/config/MessageKeyConfig.java
  src/main/java/com/prgrms/prolog/global/image/api/ImageController.java
  src/main/java/com/prgrms/prolog/global/image/util/FileManager.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/prolog/global/jwt/JwtAuthenticationToken.java
  src/main/resources/messages/exceptions/exception.properties
  src/test/java/com/prgrms/prolog/global/jwt/JwtAuthenticationTest.java
Labels: ♻️ refactor

#106 [#105] 프로젝트 마무리 정리하기(3차 스프린트)
  .env.example
  README.md
  sample_env
  src/docs/asciidoc/api.adoc
  src/docs/asciidoc/api.html
  src/main/java/com/prgrms/prolog/domain/series/api/SeriesController.java
  src/main/java/com/prgrms/prolog/domain/series/repository/SeriesRepository.java
  src/main/java/com/prgrms/prolog/domain/series/service/SeriesServiceImpl.java
  src/main/java/com/prgrms/prolog/domain/user/api/UserController.java
  src/main/java/com/prgrms/prolog/domain/user/dto/UserDto.java
  src/main/java/com/prgrms/prolog/domain/user/model/User.java
  src/main/java/com/prgrms/prolog/domain/user/service/UserService.java
  src/main/java/com/prgrms/prolog/domain/user/service/UserServiceImpl.java
  src/main/java/com/prgrms/prolog/global/config/JpaConfig.java
  src/main/resources/db/migration/V3.1__delete_unused_table.sql
  src/test/java/com/prgrms/prolog/domain/like/api/LikeControllerTest.java
  src/test/java/com/prgrms/prolog/domain/series/api/SeriesControllerTest.java
  src/test/java/com/prgrms/prolog/domain/series/repository/SeriesRepositoryTest.java
  src/test/java/com/prgrms/prolog/domain/series/service/SeriesServiceImplTest.java
  src/test/java/com/prgrms/prolog/domain/user/api/UserControllerTest.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: 📝 docs, release

#107 AWS 지원 종료 이후 github action workflow 업데이트
  .github/workflows/docker-push-and-aws-run.yml
  .gitignore
  src/main/java/com/prgrms/prolog/global/file/api/FileController.java
  src/main/java/com/prgrms/prolog/global/file/dto/UploadFileResponse.java
  src/main/java/com/prgrms/prolog/global/file/util/FileManager.java
  src/main/java/com/prgrms/prolog/global/file/util/UploadFileToS3.java
Labels: ♻️ refactor, 🐥CI/CD

#108 readme 업데이트
  README.md
Labels: 📝 docs
